on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION'
name: "Versioning"
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Generate VERSION file
      run: git log -1 --format=%cd --date=format:'%Y.%m.%d' > VERSION
    - name: Commit file
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      continue-on-error: true
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git checkout main
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add VERSION
        git commit -m "Update VERSION" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
